spring.application.name=mcsv-inscripciones

server.port=8003

spring.datasource.url=jdbc:postgresql://localhost:5433/mcsv-inscripciones
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


spring.jpa.generate-ddl=true
logging.level.org.hibernate.SQL=debug

#Ésta configuracion es para evitar que me de error en los tipos de datos en la base de datos
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
