spring.application.name=mcsv-inscripciones

server.port=8003

spring.datasource.url = jdbc:mysql://localhost:3307/mcsv-inscripciones
spring.datasource.username = root
spring.datasource.password =
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.generate-ddl=true
logging.level.org.hibernate.SQL=debug

#Esta configuracion es para evitar que me de error en los tipos de datos en la base de datos
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
